# -*- coding: utf-8 -*-
"""Internal_Assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmAIo7iKTlGXuPU6ra46BKJ1WZDmw-Lm
"""

#q1
length = int(input("Give the length of the rectangle: "))
width = int(input("Give the width of the rectangle: "))

area = length * width

print('area of the rectablge is : ', area)

#q2

def calculate_bmi(weight, height):

    bmi = weight / pow(height,2)
    return bmi


weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))
bmi = calculate_bmi(weight, height)
print("Your Body Mass Index (BMI) is:", bmi)

#q3
def print_student_scores(scores):
    print("Student Scores:")
    for student, score in scores.items():
        print(f"{student}: {score}")

student_scores = {}
num_students = int(input("Enter the number of students: "))
for i in range(num_students):
    name = input(f"Enter the name of student {i + 1}: ")
    score = float(input(f"Enter the score of student {i + 1}: "))
    student_scores[name] = score

print_student_scores(student_scores)

#q4

age = int(input("Enter the age: "))

if age < 18:
  print('User is minor')
elif age >= 18 and age < 60:
  print('User is Adult')
else:
  print('User is Senior')

#q5
for i in range(1,50):
  if i%2==0:
    print(i)

#q6
flag = True
crr_pass = input("Enter the password: ")
while(flag):
  password = input("Re-enter the password: ")

  if password == crr_pass:
    print("password confirmed")
    flag = False
    break

#q7

def calculate_average(numbers):
  if not numbers:
    return 0
  sum = 0
  for i in range(len(numbers)):
    sum = sum + numbers[i]
  average = sum/len(numbers)
  return average
num = int(input('How many numbers of which you want the average: '))
numbers = []
print("Input the number: ")
for i in range(num):
  n = int(input())
  numbers.append(n)

calculate_average(numbers)

#q8
def count_vowels(string):

    vowels = {'a', 'e', 'i', 'o', 'u'}
    count = 0
    string = string.lower()
    for char in string:
        if char in vowels:
            count += 1

    return count

input_string = input('Enter a word: ')
print("Number of vowels in the string:", count_vowels(input_string))

#q9

import datetime

def print_current_datetime():
    current_datetime = datetime.datetime.now()
    print("Current Date and Time:", current_datetime)
print_current_datetime()

#q10

def add_numbers(a, b):

    try:
        num_a = float(a)
        num_b = float(b)
        result = num_a + num_b
        return result
    except ValueError:

        return "Error: Both inputs must be numeric."


num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")

sum_result = add_numbers(num1, num2)
print("Result of addition:", sum_result)

#q11
def get_integer_input(prompt):
    while True:
        try:
            user_input = input(prompt)
            integer_value = int(user_input)

            # If the conversion is successful, return the integer value
            return integer_value
        except ValueError:
            print("Error: Please enter a valid integer.")

number = get_integer_input("Enter the input: ")
print("You entered:", number)

#q12
def divide(a, b):
    try:
        result = a / b
        return result
    except ZeroDivisionError:
        print("Error: Division by zero is not allowed.")
        return None

nume = float(input("Enter the numerator: "))
denom = float(input("Enter the denominator: "))
division_result = divide(nume, denom)
if division_result is not None:
    print("Result of division:", division_result)

#q13
def write_to_file(filename, text):
    with open(filename, 'w') as file:
        file.write(text)
filename = "hello_python.txt"
text = "hello, python!"
write_to_file(filename, text)

#q14
def read_from_file(filename):
    with open(filename, 'r') as file:
        content = file.read()
    return content
filename = "hello_python.txt"
file_content = read_from_file(filename)
print("Content from the file:")
print(file_content)

#q15
def append_to_file(filename, text):
    with open(filename, 'a') as file:
        file.write(text + '\n')

append_to_file("hello_python.txt", "i love latentview.")


with open("hello_python.txt", 'r') as file:
    file_content = file.read()

print("Content from the file after appending:")
print(file_content)